version: "3.7"
services:
  node:
    depends_on:
      - db
    image: node:6.9.1
    container_name: web
    ports:
      - published: 3000
      - target: 3000
    working_dir: /work
    environment:
      - MONGO_IP=db
      - NODE_ENV=${NODE_ENV}
    command: node /work/servier/js
  mongo:
    image: mongo:3
    container_name: db

  test:
    depends_on:
      - web
      - db
    image: node:6.9.1
    working_dir: /work
    volumes:
      - ../work
    environment:
      - NODE_ENV=${NODE_ENV}
    command: ["curl", "-s", "http://web:3000"]
